### ISSUE TITLE
No files for the bottom window

### ISSUE THREAD

**Issue by Eloren1** [flurples/C-13X#2]
There is no files for the «clear window on the back to display wiring». Do you have DXF file for this? How does it mount to the bottom?

**Comment by flurples** [comment]
I figured since it's a DIY project, different people would have different solutions to putting the window there. In my case, I just cut up an aliexpress keycap tray and double sided taped it to the inside - if you want a fancier option, you could probably laser cut some acrylic and use some sort of glue but it's all up to you

**Comment by Eloren1** [comment]
Good solution, enough for this project. Thanks.

**Comment by Eloren1** [comment]
Oh, and one more question. Did you print without these mounts so gaskets would fit instead? 

![image](https://user-images.githubusercontent.com/46666053/165806171-e32f5d40-a047-4fc6-b645-63510b7cb26f.png)

**Comment by flurples** [comment]
there are there on purpose, to provide a template on where to stick the gaskets, and they're raised to compress them slightly so the plate is more secure

**Comment by Eloren1** [comment]
So the gaskets only stick to the bottom case?

**Comment by flurples** [comment]
they go on both top and bottom
